[cgi_environ]
DIR_UPLOAD			= "./demo/www/upload"
GATEWAY_INTERFACE	= "CGI/1.1"
CGI_EXEC			= "/usr/bin/php"
SERVER_SOFTWARE		= "UN TITRE CUSTOOOOM"
# Après tu mets ce que tu veux là dedans, je sais pas trop ce
# dont t'as besoin mais bon
