[http] # pourquoi ça ne marche pas quand il n'y est pas ?

[listener]

[listener.gc]
index = "index.html" # Default index
include = ["demo/mime_types.toml"] # For testing
port = 4242
listen_backlog = 512

[listener.gc.server]
root = "./demo/www/" # Path to demo html
name = "Groenland"

[listener.gc.server.log] # TODO: server logging
enable = false
file = "logs/webserv.log"
# NGINX has a log_format field, that's pretty cool

[listener.sans_nom]
port = 5000
listen_backlog = 512

[listener.sans_nom.server]
root = "./demo/www2/"
name = "42 webserv"

[listener.colors]
port = 8080
listen_backlog = 512

[listener.colors.blue]
root = "./demo/servers/blue/"
domain = "locahost"
name = "blue"

[listener.colors.green]
root = "./demo/servers/green/"
domain = "127.0.0.1"
name = "green"

[listener.colors.noir]
root = "./demo/servers/noir/"
domain = "192.168.13.128"
name = "noir"

[listener.colors.red]
root = "./demo/servers/red/"
domain = "0.0.0.0"
name = "red"
