[http]
index = "index.html" # Default index
include = ["demo/mime_types.toml"] # For testing
port = 4242
listen_backlog = 512

[http.server]
root = "./demo/www/" # Path to demo html
name = "42 webserv"

	[server.log] # TODO: server logging
	enable = false
	file = "logs/webserv.log"
	# NGINX has a log_format field, that's pretty cool
